---
git:
  config:
    'user.email': github-actions@github.com
    'user.name': github-actions
  unshallow: true
semver:
  modes:
    detection:
      patch:
        - 'fix/'
      minor:
        - 'feature/'
      major:
        - 'release/'

