[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = "v"
fetch = false

[semver]
mode = "auto"

[semver.detection]
patch = ["fix/"]
minor = ["feature/"]
major = ["release/"]
