[git]
unshallow = true

[git.config]
"user.email" = "github-actions@github.com"
"user.name" = "github-actions"

[git.tags]
prefix = "v"

[semver.modes.detection]
patch = ["fix/"]
minor = ["feature/"]
major = ["release/"]
