[git]

[git.config]
email = "github-actions@github.com"
name = "github-actions"

[git.tags]
prefix = "v"
fetch = false

[semver]
mode = "auto"

[semver.detection]
patch = ["fix/"]
minor = ["feature/"]
major = ["release/"]
