[git]

[git.config]
"user.email" = "github-actions@github.com"
"user.name" = "github-actions"

[git.tags]
prefix = "v"
fetch = false

[semver.modes.detection]
patch = ["fix/"]
minor = ["feature/"]
major = ["release/"]
